# View and Explore TSV Files
This notebook displays the top 30 rows of all `.tsv` files found in the `train` and `test` folders.

In [3]:
import pandas as pd
import glob
import os

# Path to the dataset directory
dataset_dir = '../student_resource/dataset'

# Find all TSV files in train and test folders
train_files = glob.glob(os.path.join(dataset_dir, 'train', '*.tsv'))
test_files = glob.glob(os.path.join(dataset_dir, 'test', '*.tsv'))
tsv_files = train_files + test_files

for file_path in tsv_files:
    print(f"\n{'='*80}")
    print(f"File: {file_path}")
    print(f"{'='*80}")
    try:
        # Read and display top 30 rows
        df = pd.read_csv(file_path, sep='\t', nrows=50)
        display(df)
    except Exception as e:
        print(f"Error reading {file_path}: {e}")

================================================================================
File: ../student_resource/dataset\train\train_ground_truth.tsv
================================================================================

   source1_entity_id                                 matched_entity_ids
0          S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1        S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2       S1-343815751             S2-790675320,S2-479876582,S3-878454467
3       S1-656753428              S2-153058913,S2-24659151,S3-679606215
4       S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5        S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6       S1-318373630                          S2-660036492,S3-804600254
7        S1-86989137                          S3-274817120,S3-312496301
8        S1-29845983                          S2-648035184,S3-588502663
9       S1-789009573              S2-383871912,S3-74481402,S3-576451439
10      S1-730934468                          S2-356983532,S3-352439310
11        S1-7293388  S2-7028416,S2-442723188,S2-157073701,S3-523120965
12      S1-546142636  S2-487600131,S2-582477216,S2-392804085,S3-2000...
13      S1-274126313  S2-736616474,S2-680265918,S2-51486805,S3-92563...
14      S1-145361722              S2-120366543,S2-939389287,S3-96572514
15      S1-503957000  S2-994658326,S2-235117490,S2-353308450,S2-1732...
16      S1-692000596                          S2-580419223,S3-164220452
17      S1-561341312                          S2-483615364,S3-619529814
18      S1-777597828                          S2-836452886,S3-413669121
19      S1-282467635                          S2-938895481,S3-138350041
20      S1-727602285  S2-976870196,S2-947230367,S2-23141904,S2-13866...
21      S1-302869473                                                NaN
22       S1-65263544  S2-881122703,S2-998270769,S2-180463458,S3-4034...
23      S1-840162906  S2-129529678,S3-800978181,S3-139858754,S3-7626...
24      S1-264156494             S2-184087846,S3-562014765,S3-544213330
25      S1-567308588  S2-191200521,S2-964733072,S2-226928496,S3-5959...
26      S1-292935703  S2-195749344,S2-617410789,S2-516200703,S3-4214...
27      S1-439810025                          S2-983636768,S3-975833735
28      S1-525304403             S2-815373751,S2-293401164,S3-477957595
29      S1-314714647  S2-968477409,S2-46909251,S3-837108914,S3-19280...
30      S1-616588883             S2-603899205,S3-200505774,S3-625680391
31       S1-72310418  S2-516305116,S2-11779506,S3-570980846,S3-73116...
32        S1-9962387               S2-15221089,S3-160760047,S3-13637230
33      S1-463669205                          S2-301757320,S3-242940401
34      S1-116043204                                        S3-85523430
35      S1-818149988  S2-489380965,S2-178277614,S2-172270636,S3-9655...
36      S1-876102895  S2-358560681,S2-791711694,S3-949391374,S3-8560...
37      S1-262997549                                                NaN
38      S1-730719211  S2-467798366,S2-61695240,S2-241456014,S3-95183...
39      S1-491795528  S2-910694348,S2-977672203,S2-707708907,S3-4492...
40      S1-508022910                                                NaN
41      S1-473377609                                       S3-433876173
42       S1-72444401  S2-973800896,S2-9053863,S2-472011237,S2-503949...
43       S1-67172650  S2-555166797,S2-74945214,S3-251407198,S3-52028...
44      S1-131928575  S2-316703436,S2-529222224,S3-504772212,S3-1346...
45      S1-574308285             S2-961415907,S3-163492874,S3-875723263
46      S1-225984658                          S2-581845376,S2-355430647
47      S1-842533642  S2-352625664,S3-764018977,S3-553570072,S3-4291...
48      S1-736418916                          S2-458035790,S2-271186953
49      S1-439203009                                       S3-967165288

================================================================================
File: ../student_resource/dataset\train\train_source1.tsv
================================================================================

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India
5,S1-851869949,Custom Wealth Services LLC,"OH, Columbus, 5559 Orville Avenue",US
6,S1-785847572,Consulting Nyasa Nursing Private Limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",India
7,S1-27541239,Nexus Anchor Rain,"1111 Church Street, Unit 2007, Nashville, TN",US
8,S1-629417405,Moore Bitwise Inc,"337 Oakland Avenue, Michigan City, IN",US
9,S1-22305073,Dermatology Green Medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",US
10,S1-504790211,Crystal Lending PC,"11643 Prosperity Road, South Jordan, UT",US
11,S1-564729135,Dream Construction Limited,"H.No.16-11-23/37/A, 2Nd Floor, Flat No.207, Sa...",India
12,S1-236312382,"Kelly Advisory, Inc","301 1st Street, Chokio, MN",US
13,S1-865131206,Helios,"66 Edgewood Street, Bridgeport, CT",US
14,S1-626914593,Unified Choice Dynamix,"Unit BUILDING 3030, MD, 2701 Eastern Boulevard...",US
15,S1-765734254,Health Fellowship Partners,"601 Oleander Circle, Virginia Beach City, VA",US
16,S1-82053739,Smart Healthcare Private Limited,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",India
17,S1-309349399,Callicoat & Dailey Inc,"Charlotte, NC, 833 Reliance Street",US
18,S1-221443075,Iris Advisors,House No-777 Raghubir Bhawanmadan Pur Khadar S...,India
19,S1-341506266,Secunderabad Park Private Limited,"Secunderabad, Hyderabad, Plot No.53, Flat No.4...",India
20,S1-990319941,Holy Synagogue,"Sapulpa, OK, 2204 Park Street",US
21,S1-597762257,Green Logistics Private Limited,"E-7, Second Floor, New Delhi, South Delhi, Delhi",India
22,S1-661315962,Scott Eagle Inc,"4828 Hedges Avenue, Kansas City, MO",US
23,S1-716574008,Rajani Enterprises of Kannur,"46/1106, Dhanalakshmi Road, Near Amani Auditor...",India
24,S1-985038901,"Schaefer, Michael and Silver Associates","32876 Circle Drive, Millsboro, DE",US
25,S1-404435514,Colline Molitor Sea LLC,"5620 Trinity Road, Unit 103, Raleigh, NC",US
26,S1-252242682,"Aggie E. Nagle, L.C.S.W.","11900 54th Avenue, Plymouth, MN",US
27,S1-981440385,Angad Multitrade Ltd,"Building No. 37/4, First Floor Opp Bharata Mat...",India
28,S1-883973644,Global Hovnanian LLC,"4024 39th Avenue, Seattle, WA",US
29,S1-17666546,Pacific Learning Laboratories LLC,"4810 Nassau Avenue, Sand Springs, OK",US
30,S1-513115995,Thomas Calisa,"126 D Street, Pittsfield, ME",US
31,S1-791217329,Indian Brothers Private Limited,"#17/1, Lower Ground Floor, 1St Cross, Lalbagh ...",India
32,S1-602913883,Cascade Allied Telecom LLC,"165 Linden Street, Unit 106, Wellesley, MA",US
33,S1-401372098,Apex Inc,"108 Richardson Street, Bethany, WV",US
34,S1-796227187,Foot & Ankle Allied Center LLC,"1216 Preston Avenue, Charlottesville City, VA",US
35,S1-945437722,Joeann Hills Park Inc.,"10101 Threave Road, Unit 301, Raleigh, NC",US
36,S1-982210261,Mayur Hospital of Gondal,"C/O Dwarkadhis Enterprise, C.M. Palace, Ist Fl...",India
37,S1-976369483,FUE Pgim Care,"211 Dewey Road, IL, Rockton",US
38,S1-370715897,Primary Care Physicians Inc.,"53 Park Lane, Wellsville, NY",US
39,S1-27029362,Global Ministries,"74 429, Stockdale, TX",US
40,S1-145829425,North Storage Care,"2804, Tower A, Sarova, Samata Nagar, Kandivali...",India
41,S1-993527714,George Saul Inc,"Unit UNIT 367, 1400 Great Wolf Drive, WI, Vill...",US
42,S1-965555167,Siobhan's Bike Shop LLC,"1644 Crownsville Road, Fl 0, Crownsville, MD",US
43,S1-151608539,Orchid Renewable Ltd,"House No.26-352, Kadavakollu Bhavanam, Bhuttai...",India
44,S1-714672596,Foot & Ankle Patriot Group,"325 Cross Street, Unit LOT 1A, Anderson, IN",US
45,S1-134898809,Corner Hypnosis,"26 Stone Street, Unit 3, Beverly, MA",US
46,S1-500841209,Bautista Properties LLC,"7196 State Route 14, Mcleansboro, IL",US
47,S1-855787505,Blue Steels Limited,"12, Floor 2, Plot-750, 20, Satnam Nagar, Dr G ...",India
48,S1-277072715,Shiva Management Private Limited,"D No. 20-6-3/12, Dantuluri Vari Street, Ayodya...",India
49,S1-269656551,Impetus Hotel Public Limited,"Canal Road Wakdai Nagar, Mangaon, Raigarh, Mah...",India

================================================================================
File: ../student_resource/dataset\train\train_source2.tsv
================================================================================

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US
5,S2-138046867,Lee and Lawson,"1702 Pine Avenue, CITY OF MENOMONIE, WI",US
6,S2-584977605,SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPOR...,"H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab",India
7,S2-277444929,Shree Infracon Private Ltd,"63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKH...",India
8,S2-721031885,Chavira Platinum Chimera LLC,"282 SAXONY DRIVE, FTT MITCHELL, KY",US
9,S2-508602797,FOUNDATION EXCEL AGENCY PRIVATE LIMITED,"HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, M...",India
10,S2-69394310,heassociates.com,"599 PEASE HILL ROAD, HORICON, NY",US
11,S2-615967906,सन कंस्ट्रक्शंस प्राइवेट लिमिटेड,"43 SUKH SAMRUDDHI, Maharashtra, PUNE REGION, P...",India
12,S2-684635925,Global Developers Medicals Private Limited,H.NO 008 GOVIND BUILDING OPP.HOTEL VRINDHAVAN ...,India
13,S2-868087865,ASSET BUILDING COALITION LLC,"8219 17RD STREET, LAKE STEVENS, WA",US
14,S2-795141272,Olszewski Holding Company LLC LLC,"218 SHOAL CREEK, WILLIAMSBURG, VA",US
15,S2-414418413,CANDY'S-SERVICES,"313 FOXBOROUGH DRIVE, BRUNSWICK, OH",US
16,S2-566688803,रियल मॉडर्न फूड लिमिटेड,"SHP NO. G-4, PLOT NO. 19, SECTOR 42, NERUL, TH...",India
17,S2-634015823,Crestline Crestline Clean LP,"HIGHWAY 49, ASHLAND CITY, TN",US
18,S2-378707035,Nion,"7100 BRIGHAM ROAD, HENRICO COUNTY, VA",US
19,S2-953098128,Keystone Odyssey Odyssey LLC,"1418 MEADOWBROOK DR, JOHNSON CITY, TN",US
20,S2-526991413,Jones Royal Bancshares,"61573 FRIENDSHIP LN, CNROE, TX",US
21,S2-879667609,குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்,"#C-21 - S, AMBATTUR, CHENNAI, Tamil Nadu",India
22,S2-202057528,Altitude Retail,"C7 419BONNY BUILDING KATTOOR P O, MALAPPURAM, ...",India
23,S2-763108962,Core Welfare Society LLP,"PLOT NO Q-17 KH. NO. 48/19 GROUND FLOOR ONLY, ...",India
24,S2-415733261,Sweet Barbershop (Co),"05131 COPPER MEADOW LN, WEST JORDAN CITY, UT",US
25,S2-294835210,COBALT (LLC),"NC, CANLER, 110 MEADOWBROOK ACRES",US
26,S2-944853638,Piedmont Complete Chile L.L.C.,"259 1/2 CAVALIER WAY, BURLINGTON, NC",US
27,S2-235039028,Empire School of Medicine,"0477 MELISSA COURT, GAHANNA, OH",US
28,S2-783158461,Animal Welfare Nétwork,"260 CADILLAC DR, SACRAMENTO, CA",US
29,S2-669879950,"Hail, Harris & Roberts Inc","8 WENTWORTH AVE, STOUGHTON, MA",US
30,S2-673704658,Behavioral Health Anchor Care,"1715-1719 Orchard Blossom Drive, CITY OF APPLE...",US
31,S2-133664209,Bay Bdc Co,"DC, WASHINGTON, 2117 F STREET",US
32,S2-49714549,CLASSIC [TECHNOLOGIES],"Rajasthan, HN G-103 113, VRINDAVAN VIHAR, DCM,...",India
33,S2-401480583,Division of Sanitation,"IN, 2178 WILLOW LANE, PERU",US
34,S2-54307441,LLC METRO COALTIMN,"SAVORY LANE, FELTON, DE",US
35,S2-91305348,Swastik Impex Private Ltd,"8-2-595/3/8A-8B, EDEN GARDENS, ROAD NO.10, KHA...",India
36,S2-73037424,Eye Valley Medicine Incorporated,"39 MAIN STREET, SAVONA, NY",US
37,S2-332014708,Direct Acadia Inc,"CURTIS STREET, TOLEDO, OH",US
38,S2-40574852,TATAA BEST AGRICULTURE,"1225 GUMWOOD DRIVE, OH, PLEASANT TWP",US
39,S2-836840386,[INCORPORATED] PEAK TRADIN6 NETWORKS SOUTHSIDE,"2062 SMITH HOLLOW RD, BLAINE, TN",US
40,S2-208005980,Solstice LLC,"303 MCCORD ROAD, ROUNDUP, MT",US
41,S2-978126813,Private Ambernath Sólar Limited,"PLOT NO B-78/1, ADDITIONAL MIDC ANAND NAGAR, A...",India
42,S2-257885603,Apex Preferred Strategy Inc,"2467 EDDINS ROAD, DOTHAN, AL",US
43,S2-428899461,Roopant Pvt Ltd Partners,"HN 247 A/109, MINI MARKET CO-OP. HSG. SOCIETY ...",India
44,S2-125007797,"Doolittle, Hasvey and Hardy","2017 COBBLESTONE DRIVE, COLOGNE, MN",US
45,S2-647437327,G-P Starkey Motor,"7336 MAITLAND LN, CHARLOTTE, NC",US
46,S2-838526909,Highland Arc Inc.,"WA, FEDERAL WAY, ##2326 341ND PLACE",US
47,S2-912941112,JEN ELWOOD ART5 CENTER,"145 CR 2729, MICO CCDP, TX",US
48,S2-511731036,Vantageavigild,"067 PRODUCTION CT, NULL, INDEPENDENCE, KY",US
49,S2-653150968,prprivate.com,"ROYAL ARCHID SECOND FLOR, GITGUJARI 4/8 CORNER...",India

================================================================================
File: ../student_resource/dataset\train\train_source3.tsv
================================================================================

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India
5,S3-578159284,LLC Hernandez Colonial Redwood,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...",US
6,S3-121412624,Classic Equity Partners Group,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...",US
7,S3-249416830,Ectolumdrex dba X+ Madison Inc,"S03575 Cty Tk M, Town Of Buffalo, WI",US
8,S3-107644605,Animal Hanisch Hospirlg,"##8 Willow Oak Lane, Fl. 0, Saint Louis, Missouri",US
9,S3-160217003,Gomez Optimal,"343 Hempstead 161, Hope, Arkansas",US
10,S3-504183980,The Rapid Learning Alliance LLC,"46 White Rock Dr, Hurricanne, West Virginia",US
11,S3-53737228,Indian Care Public Limited,"Raebareli, Rae Bareli, Raibareilly, UP, No #51...",India
12,S3-16693061,Béque,"189 Connmre Dr, Nashville, Tennessee",US
13,S3-331103166,#centraleducation,"1113 Ash Street, Carlsbad, New Mexico",US
14,S3-45067784,அரிஹந்த் Foundation Private Limited,"Saranampatti Roadvellakinar Post Coimbatore, T...",India
15,S3-118652570,Wildlife Guild LLC,"18900 Harl Weiller Road, Caldwell, Ohio",US
16,S3-90100170,Cinder Charlton-PC,"0200 Washington Street, ALVO, Nebraska",US
17,S3-476778426,ZRO Trinity Co,"0315 Laramie St, Gillette, Wyoming",US
18,S3-128062172,Bajaj Foundation Private Limited,"Rajendra Nagar, Andhra Pradesh, 221, 2Nd Floor...",India
19,S3-171901473,Estell's Creative,"15380 Fillmore Street, Unit 1006, Goodyear, Ar...",US
20,S3-973629095,Center 5uperior Co,"144 Foster Avenue, Harriman, Tennessee",US
21,S3-554084947,Palace Vidyalaya,"Plot No.: 3829/3250, Near Metro Pillar No: 234...",India
22,S3-315861895,Global Applied,"Tiger Lily Lane, Madison, Indiana",US
23,S3-326049086,Integrated Business Systems,"#111 Frontage Road 2121, Ilfeld, New Mexico",US
24,S3-181819854,Cardiology Heartland Cáre Associates #98825,"Tennessee, 607 Fourth St, Columbia",US
25,S3-776815069,Sai Surgical (India) Ltd,"Unit A3, Ugf, Plot No. 17, Satbari Vill., Chat...",India
26,S3-230314480,MW Management Private Limited - 2067865001,"Pt No 18, Nagpur, MH",India
27,S3-807500071,FERRERO FERRERO DUKE,"1516 Marshall St, Iowa, PMB 2592, Boone",US
28,S3-878295053,Chinglepet Private Limited Center,"4-2, TN, Kanchipuram, Chinglepet",India
29,S3-725749046,Modern Center Brothers,"Shop No. 188, 1St Floor, Powai Plaza Cts No. 5...",India
30,S3-298996001,Navkar Sons Ltd Center,"No. 562 X/1725, Main Road, Rajgarh Colony, Eas...",India
31,S3-32805948,സിൽവർ കൺസൾട്ടൻസി പ്രൈവറ്റ് ലിമിറ്റഡ്,"Ernakulam, KL, 18/479E/3 Peringattil Tower Kan...",India
32,S3-256812623,ब्लू टेक्नोलॉजीज,"MH, East Garo Hills, 2, Swadhin Sadan, C-road,...",India
33,S3-822866561,Compher's Auto Glass,"4301 Broadway Ave, Evansville, Indiana",US
34,S3-726575561,గుజరాత్ Logistics లిమిటెడ్,"H.no 4-0 Flat No. 103, Sai Bhavana Encl Kamala...",India
35,S3-572363539,Stellar + Brothers Private Ltd,"A-401, Kamlesh Apartment, Sher-e-punjab Colony...",India
36,S3-551148968,Ear N0se & Throat Regional,"25 Eighth Avenue, Haverhill, Massachusetts",US
37,S3-738829801,"Best Software Innovations,","Edwall, Washington, 29511 Tucker Prairie Rd",US
38,S3-566665563,Capital-Snow Capital-Snow Corporation,"367 Parkland Way, Chanhassen, Minnesota",US
39,S3-575167920,SAV Holdings,"87, Patna Dairy Project, Haroon Nagar Colony S...",India
40,S3-586800406,Mr Om-Consultants Corporation,"F-0017, Eternity Mall Premises Chs Ltd. Near T...",India
41,S3-190231775,Cozy Shop Bike,"Mulberry Dr, NULL, Buckeye, Arizona",US
42,S3-323153716,LLC Safe Newbury,"Evening Star Way, Sequim, Washington",US
43,S3-783004558,Shree Sgpeciarity Pvt. Ltd.,"348, Radhna, Inayatpur, Meerut, UP",India
44,S3-159562080,Little Ice Cirhm,"1148- Heritage Ct, FT. Mill, South Carolina",US
45,S3-397850436,Hmgreen.Com,"603, Thane, Palghar, MH",India
46,S3-244694796,TV Tower Inc.,"Sand Hills Drive, Surprise, Arizona",US
47,S3-755888332,lakshmi medical-mumbai ventures,Door No 180-B Tanna Residencyveer Savarkar Mar...,India
48,S3-875583147,Orthopedic Specialists Of Fort Wht LLC,"3900 Sanguinet Street, Fort Worth, Texas",US
49,S3-27936464,erwinsignaturekrakacquisition.com,"817 C-Bar Ranch Trl, Cedar Park Township, Texas",US

================================================================================
File: ../student_resource/dataset\test\test_source1.tsv
================================================================================

,entity_id,business_name,business_address,country
0,S1-714132312,Zephay Labs Inc,"2621 Cotten Road, Tyler, TX",US
1,S1-106407869,Vision Partners Corp,"IA, Iowa City, 1064 Newton Rd, Unit 11",US
2,S1-156285671,<< Team Ecole,"175 Boulevard du Président Franklin Roosevelt,...",France
3,S1-689823050,Red Perfect Trading,"Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...",India
4,S1-921369899,ZNB Club SARL,"Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...",France
5,S1-481669221,Nandlal Kisan LLP,"D-61 Ifs Apartmentmayur Vihar I, New Delhi, Ea...",India
6,S1-909865979,Cure Seafood,"1325 Brooklyn Walk, Issaquah, WA",US
7,S1-280204013,Om Constructions Pvt Ltd,"Karauli, Rajasthan, Karauli, Pani Ki Tanki Ke ...",India
8,S1-742053041,Roongta Sangh,"Bhubaneswar, Sub Plot No.-L6/29, Mahodadhi Bha...",India
9,S1-913506265,Thermal & Fils SASU,"20 Rue Parmentier, Dunkerque, Hauts-de-France",France
10,S1-479574617,Anupama Estates Pvt Ltd,"26, Ram Nagar, Behind M.C Quarters Near Jagadh...",India
11,S1-680637447,Siliguri Media Pvt Ltd,"S No. 42/2/3, H No. B/5, Santkrupa Niwas, Ramn...",India
12,S1-870190130,Naman Trust,"60 Kashipuri Kabirkhedi, Indore, Madhya Pradesh",India
13,S1-365170694,Consulting Sai Nanak Private Limited,"A-115, Freedom Fighter, Enclave Neb Sarai, Sou...",India
14,S1-778640743,Blinny Gordon Apex Rate,"100 Hartsdale Avenue, Unit Apartment TPE, Gree...",US
15,S1-378191895,East Marketing Private Limited,"Howrah, 2, West Bengal, India Exchange Place, ...",India
16,S1-684974736,Garcia Mercury Corp,"600 SE 2nd St, Pelican Rapids, MN",US
17,S1-750279127,Sra Export,"A-73, Lajpat Nagar-I, New Delhi, South Delhi, ...",India
18,S1-209281220,ZH Plus Private Limited,"37B, Pushtikar Chs Ltd, Shiv Sadan, Near Patel...",India
19,S1-550154910,Tech Management Private Limited,"H No. 16-2-751/A/70, Kara, Chanchalguda, New M...",India
20,S1-897975128,Prime Aditya Agro,"1-76, Brahmanapalli Village, Andole Mandal, Jo...",India
21,S1-704604312,Market Sciences (India) Ltd,"A-15 Phase-10, Shiv Vihar, Karawal Nagar, Delhi",India
22,S1-628750886,Grain & Fils,"Lille, 329 Avenue de Dunkerque, Hauts-de-France",France
23,S1-714038427,Delta Partners Inc,"2202 Brandywood Drive, Murfreesboro, TN",US
24,S1-426194890,Midwest Alliance LLC,"1045 Lazy Acres Road, Protem, MO",US
25,S1-122385784,Castaneda Capital LLC,"105 Paula Boulevard, Brookhaven, NY",US
26,S1-540642140,Tri-State Network,"3105 Stonegate Drive, Paragould, AR",US
27,S1-123475953,Sankalp India,"New Delhi, South Delhi, Ii Nd Floor Malviya Na...",India
28,S1-444801830,Site Win Private Limited,"F-47 501 Rasta Peth Pune, Pune, Maharashtra",India
29,S1-502376041,Chayan Trading Private Limited,"Flat No 404, Block-1, Rbr Complex, Miyapur Ser...",India
30,S1-594021398,Abohar Logistics Pvt Ltd,"C/O Manoj Kumar St No. 1, Model Town Sunder Na...",India
31,S1-261170522,Reid Can LLC,"1404 Irving Hill Drive, Knightdale, NC",US
32,S1-466641145,Elephant Centre EURL,"30 Rue Lachassaigne, Bordeaux, Nouvelle-Aquitaine",France
33,S1-99245709,Skyking Enterprise LLP,"A-606, Sankalp Iconic Tower, Near Iscon Cross ...",India
34,S1-339015166,Brzee Law Chambers,"No.7Groundfloor, Mhtresidence Green Orchrds La...",India
35,S1-614259237,Lilia Prosser Generating LLC,"123 Dorchester Court, Waukegan, IL",US
36,S1-385801270,Maison de Santé Generation,"30 Rue Louis Thénard, Saint-Nazaire, Pays de l...",France
37,S1-334672926,Traify Superior Pharmaceuticals,"19 Laurel Ridge Court, Wallingford, CT",US
38,S1-717749279,Saint-Herblain Societe SARL,"5 Impasse Jean Baptiste Clément, Saint-Herblai...",France
39,S1-564662660,"Fregoso, Andrews and Reed Biotech Associates","25246 33 Avenue, Saint Cloud, MN",US
40,S1-41643447,R M V Ii Stage Storage Pvt Ltd,"Opp H I G House 233, Dollars Colony I Main, Ba...",India
41,S1-581360597,Pediatric Dentistry Pacific Physicians PC,"9121 Susie Lane, Little Rock, AR",US
42,S1-946184931,Quartz L.L.C.,"56 Rock Hill Circle, NC, Asheville, Unit 65",US
43,S1-244940399,Goenka & Co,"D 2054A Palam Vihar, Gurgaon, Haryana",India
44,S1-616465752,Association de Pena,"21 Chemin de la Traverse, Bordeaux, Nouvelle-A...",France
45,S1-762904067,Green Global Private Limited,"F-85, Ist Floor, Lsc, Vardman Mall, Nehru Viha...",India
46,S1-261476747,Securite Darts Sport SARL,"21 Chemin des Réunis, Nantes, Pays de la Loire",France
47,S1-874436225,Galaxy Power Private Limited,"Shop No 4-5-13-14 Paras Plaza, K C Jain Nagar,...",India
48,S1-816918307,Guru Shiva Technology,"C/O Chandan Mallick, Shop 16 R A Enclave Groun...",India
49,S1-52153457,Indo Infrastructure Private Limited,"N 161 A, Saira Tower, 3Rd Floor Commercial Com...",India

================================================================================
File: ../student_resource/dataset\test\test_source2.tsv
================================================================================

,entity_id,business_name,business_address,country
0,S2-192345572,Brahma Infosoft,"COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...",India
1,S2-566025912,Marina Ecole France Sarl,"63 R. DE DIEPPE, LILLE, Hauts-de-France",France
2,S2-158121477,SCI Ptit Àmicale,"18 RUE JEN ZAY, Dunkerque, Nord",France
3,S2-89663826,Apex Summit,"67 KENTUCKY ST, SALYERSVILLE, KY",US
4,S2-884102769,Fresh Truist,"8264 FILLY COURT, ROANOKE COUNTY, VA",US
5,S2-910351373,PVT. INDUSTRIES PMB LEASING LIMITED,"SURAT, OFFICE NO. 03038, TRADE HOUSE, NEAR RUS...",India
6,S2-229677112,Clm Agro [Limited],"G-B3/5, T V INDUSTRIAL ESTATE 248/A, S K AHIRE...",India
7,S2-770341988,sci ligue ici parents,"NO. 5 ALLÉE DES HÊTRES, Pornic, Loire-Atlantique",France
8,S2-375151053,A DIAMOND SHORT LLC,"126-B New Line Road, MORRISTOWN, TN",US
9,S2-701289183,Fanni's Dmaigesostcis,"1200 HWY 1187, CROWLEY, TX",US
10,S2-809665812,West Charter School Downtown LLC,"1462 SIXTH AVENUE, KANKAKEE, IL",US
11,S2-767997013,neha foods private limited,"CRYSTAL PLAZA, TOWER NO.1, 2ND FLOOR, 2-B GOTR...",India
12,S2-317480348,Nagpur Financial Corp,"H.NO 4/A ASHTAVINAYAK, NAGAR, NAGPUR (URBAN), ...",India
13,S2-340420883,Oncology Complete,"VA, 321 GAINSBOROUGH ROAD, VIRGINIA BBEACH",US
14,S2-715460557,First Synaighsoue Holdings,"8508 SAN ANTONIO DR, AMMARILLO, TX",US
15,S2-578788567,Kaivalya International School Infratech Priva...,"OFFICE NO. ##70, 3RD FLOOR, L.K. MARKET BUILDI...",India
16,S2-292567038,KERALA INDIA LIMITED,"P. NO. 482, KN 131 & 133 HANWANT A, BJS COLONY...",India
17,S2-779040268,supertech academy exports,"NO 54 GROUND AND FIRST FLOOR, WORLDMARK-I, ASS...",India
18,S2-378846408,BEACON CORP,"7812 COLUSA ST, PO BOX 899, PORT ORCHARD, WA",US
19,S2-726058757,Center Grand PLLC,"112 TRAVIS AVE, PRICHARD, AL",US
20,S2-504393659,All,"578 MISTY MOUNTAIN DR, OFALLON, MO",US
21,S2-530685908,Palar Projects Public Limited,"NO 43 C/O LT KAZI EKRAMULLA, BALARAMBATI, NEAR...",India
22,S2-559669701,ARCE & BELTRAN PARTNERS,"5116 80TH STREET, STILLWATER, OK",US
23,S2-891600450,KSQE Resort,"B-242 F/F, SURAJMAL VIHAR, SHAHDARA DELHI, DE...",India
24,S2-647447093,Tunisie Inter Cie International SARL,"77 AV LEON JOUHAUX, LILLE",France
25,S2-956479781,కృష్ణా ఇంపెక్స్ లిమిటెడ్,"H.NO 27TH FLOOR, Telangana, HYDERABAD, SERI LI...",India
26,S2-875724478,ૐ Foundation પ્રાઇવેટ લિમિટેડ,"#203, NARAYAN KRUPA SQUARE, B/H NATRAJ CINEMA,...",India
27,S2-77137709,Indian Investment L.L.P.,"G-202 ACE ASPIRE, SECTOR, ATUL MARG, TECHZONE ...",India
28,S2-4583532,*** Yamuica Venus Pvt Ltd,"1312C/11, GALI NO. 05 OPP. MUKHI HOSPITAL, SUD...",India
29,S2-938316135,VIOVERA TOLNS,"MA, 25 NIAGARA STREET, NULL, SPRINGFIELD",US
30,S2-357438552,Dmb Skills L.L.P.,C/O GRP SURYA PEB ENGG CONST. OFFCE NO 263 264...,India
31,S2-223826524,Rizabrix,"PUNE, GODREJ INFINITY-3A HAVELI, S.NO. ##9 TO ...",India
32,S2-600460285,Innovative Construction Pvt Ltd,"H NO-B3/2/2 NEAR SECTOR-14, EXT, DEVILAL NAGAR...",India
33,S2-537184954,ਸਕਾਈ ਅਰਿਹੰਤ ਗਲੋਬਲ ਪ੍ਰਾ. ਲਿ.,"NO 3121, WARD NO. 9 NEEM WALA CHOWK, MOHALI, S...",India
34,S2-787861634,Smt Nv & Pmtnbs,"S. NO. 129/40, BLOCK NO 8, IDEAL COLONY, KOTHR...",India
35,S2-268861424,"Bagwell, Gill and Burrows Saratoga Saratoga Ri...","#4921 234RD ST, MOUNTLAKE TERRACE, WA",US
36,S2-634571997,Ds Services Infratech Ltd,"Delhi, C-185, 1ST FLOOR, NARAINA INDUSTRIAL AR...",India
37,S2-560710588,Schmidt Third Inc,"KENNT, WA, 26443 161TH PL",US
38,S2-222871632,ACOSTA PRIME SUN LLC,"1501 ST JOHN RD, PHOENIX, AZ",US
39,S2-262646344,OZT ÀMICALE SAS,"24 R DESAIX, TOURCOING, Hauts-de-France",France
40,S2-166809876,Channel Brothers Private Ltd,"03, DHOOT INDUSTRIAL COMPLEX, RAVI SHANKAR SHU...",India
41,S2-440948455,Pártnérs Manpower Nagiya,"H.NO 111/475 BRAHMA NAGAR, KANPUR, Uttar Pradesh",India
42,S2-784442772,Si Group Limited,"BUSINESS MARKET 6, NEAR, SAVAN SIGNET, RAIYA R...",India
43,S2-742018880,QHC Culture [EURL],"68 R. DE JEMMAPES, LILLE, Nord",France
44,S2-878037834,Association du Pàrenthese,"17 RUE YVES BODIGUEL, NANTES",France
45,S2-933724724,Production Thê Jeunes,"9 B CITÉ MOUNEYRA, BORDEAUX, Nouvelle-Aquitaine",France
46,S2-744323706,ইনোভেটিভ প্রোডাক্টস রেস্টুরেন্ট লিমিটেড,"NO 39 C/O TAPAN KUMAR SAMANTA DAMODARPUR, TAML...",India
47,S2-583840796,EDWARDS CORNERSTONE FLEXIBLE L.L.C.,"SANTA YNEZ, CA, 2712 LA SELVA",US
48,S2-193013091,"Brown Cfe, LLC","732. GUDE DR, PO BOX 7187, ROCKVILLE, MD",US
49,S2-17102176,"Boyd Roofing, Inc","70 BARBARAS WAY, N/A, NEWBERG CITTY, OR",US

================================================================================
File: ../student_resource/dataset\test\test_source3.tsv
================================================================================

,entity_id,business_name,business_address,country
0,S3-462677478,मॉडर्न फाइनेंस,"No 10 Enkay Square, 448A, Udyog Vihar Phase V,...",India
1,S3-374810425,Shri Sai Infratech Co,"3/115, East Delhi, DL",India
2,S3-198586129,Fractales Amis Groupe S.A.S,"23 Rue Icmre, La Teste-de-buch, Gironde",France
3,S3-10300249,Shri Supreme Consulting Private (Limited),"H.no 910 A 3503, Mumbai, महाराष्ट्र",India
4,S3-604980231,Prime Realty Ventures Public Limited,"G.t. Karnal Road, Industrial Area, New Delhi, ...",India
5,S3-577972146,Perfect Investments Private,"Plot No.99, Flat No.201, Sri Dhama Apts., Road...",India
6,S3-150632472,Pace Mfa PC,"2132 Thomas Run Road, Bel Air, Maryland",US
7,S3-184785497,ஈஸ்டர்ன் கன்சல்டன்சி பிரைவேட் லிமிடெட்,"1410 Sri Mahalakshmi Mandiar 59, Justice Rathi...",India
8,S3-536202929,PU Pvt. Ltd. Services,"TG, Plot No-25, Hyderabad, Qutubullapur, 26, 2...",India
9,S3-560657213,Sun पावर Provision,"143-Alig Flats Rajouri Garden, New Delhi, West...",India
10,S3-934627663,Dunkerque Club,"13 Rue Jules Andrieu, Dunkerque",France
11,S3-517069981,South Bangalore Nursing,"#803 20/1, Bangalore South, Begur, ಕರ್ನಾಟಕ",India
12,S3-92755938,Engages Àrt Pharmacie SCI,"250 R De Lille, Roubaix, Hauts-de-France",France
13,S3-712130770,Europ & Frères Distribution S.A.,"(41) Rue Des Thuyas, Lège-cap-ferret, Gironde",France
14,S3-811459169,Bala India,"B-5/129 Indra Nagar, उत्तर प्रदेश, Lucknow",India
15,S3-218566871,Spring Educational Society (Company),"C-1, 1103, Emerald, Yogidham Gauripada Kalyan,...",India
16,S3-323904182,Jnc Trading Infratech Private Limited,"Kolkata, F-06, 28 No. Road Garden Reach, Kolka...",India
17,S3-715117209,Memorial Comite,"135 Rue Henri Dunant, Calais, Hauts-de-France",France
18,S3-219041197,Sai Infratech Pvt Pvt Ltd Service,"No 25 Wvn Manor, Chennai, தமிழ்நாடு",India
19,S3-468731115,Inc Arden's Tire Shop,"129 Bridge Street, PMB 9302, Hillsborough, Nor...",US
20,S3-483958914,Ameerpet Industries Infratech Pvt Ltd,"#102/A, Svss Nivas, M.no:7-2-1813/5/a/1/w101a,...",India
21,S3-185659081,INC. DELTAVERA GROWTH,"1514 Westhaven Drive, Raleigh, North Carolina",US
22,S3-127741306,Sanguine & Sssn Group Private Limited,"5B/9 Chaitanya Sankara, No.97 4Th Main Road, G...",India
23,S3-610536355,M/s Sandeep Software (India) Pvt. Ltd,"No. 73, Church Street, Bangalore North, Bangal...",India
24,S3-825495383,Savita Estates (Incdina) Group LLP,"Gat No 34, Open Plot Land, Road, Talawade Bath...",India
25,S3-995796854,Valley Best Southside LLC Services,"3419 Evergreen Ln, Portland, Oregon",US
26,S3-115653125,Sanghvi Ventures Exports Ltd,"Door No 25 Outside Jundla Gate Karnal, Karnal,...",India
27,S3-797337828,DIGITAL DESIGN INTERNATIONAL,"Carpenter Drive, Fairborn, Ohio",US
28,S3-643284918,Swing Maison SARL,NaN,France
29,S3-221443476,"Fox, Mcclusky and Powers Coastal Highland Inc.","2729 Ashley Cir, Washington, Spokane",US
30,S3-521783865,Urgent Care Innovative Partners Holdings,"##503 Parks Street, Newbern, Tennessee",US
31,S3-264170444,Sun Services Private,"#201-Samp Residency, Tps-3, Nr. Veer Saverkar ...",India
32,S3-877919199,ಡಿಜಿಟಲ್ ಬಿಲ್ಡರ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,"120Th, 3Rd Flr, 1St Main Rd, Hbr 2Nd Stage Opp...",India
33,S3-668629842,"Worsham, Flores and Minor LLC","322 Joan Avenue, Birmingham, Alabama",US
34,S3-159233685,Supreme Ville Priigtle Limited,"Door No 4Th Floor, Office 24, So, No-53, 54 Wi...",India
35,S3-305215419,Fédération de Velo SAS,"11 Rue Deregnaucourt, Tourcoing, Hauts-de-France",France
36,S3-416247723,Gill and Búrke Aspac Inc,"1579. 220th Avenue, Delmar, Iowa",US
37,S3-482581656,Krupa Farmer Ltd,"Door No 543 139G/A, NULL, Mettupalayam, Coimba...",India
38,S3-22088661,Cascade Interstate Infrastructure Corp,"331 Hammond Pond Parkway, Unit 301, Brookline,...",US
39,S3-717745791,शक्ति इम्पेक्स प्राइवेट लिमिटेड,"1335, 1St Floor, Sector 15 Part 2, Gurgaon, हर...",India
40,S3-1062100,Deleves Elémentaire,"9 Anenue De Bougainville, Lege-cap-ferret",France
41,S3-867263634,Chennai Consultants Private,"Chennai, தமிழ்நாடு, 40",India
42,S3-662721327,Dr SHIVA IMPEX PRIVATE LIMITED,"Angadi St, Venkateshpuram Colony, TN, Ayanavar...",India
43,S3-464265492,New Ágro,"G No-136/p, F No-b2/104, B2, Building Manjeet ...",India
44,S3-760959067,Brina Chico Preferred Wholesale Inc,"31 Tomer Circle, Monroe, New York",US
45,S3-125349995,Ss First Infotech LLP,"H No 1-62/K/49, Plot No 36, Floor 3 K2, Busine...",India
46,S3-526709055,Suraj Consultancy Overseas Pvt Ltd,"526 Broadway Signature, Nr. Priya Cinema Sevas...",India
47,S3-960416326,Private Jain Lakshmi Hospitality Limited,"#220-A, Ground Floor, Flat No. 100, Tower-2 Na...",India
48,S3-695502221,SKW MONEYCHANGER PRIVATE LIMITED,"#625, Sector -3, Fourth Floor Iii F, Vaishali,...",India
49,S3-276427681,Jahnvi Media Enterprises Pvt Ltd,"Flat - 324, Magnum Heights Nallagandla, Hydera...",India

## Dataset Sizes
Counting the number of rows for each TSV file in the dataset.

In [ ]:
import glob
import os

dataset_dir = '../student_resource/dataset'
tsv_files = glob.glob(os.path.join(dataset_dir, '**', '*.tsv'), recursive=True)

for f in sorted(tsv_files):
    with open(f, 'rb') as file:
        count = sum(1 for _ in file) - 1 # Subtract 1 for header
        print(f"{os.path.basename(f)}: {count:,} rows")